### PR TITLE
CIVDT-1678: Content updates

### PR DESCRIPTION
**Pull request by jacemale-hmrc**

### CODE REVIEW

**Comment by dannybassi** [comment]
Section 2 error messages have been updated on the spreadsheet. Could this also be updated

**Comment by dannybassi** [comment]
The changes to the pages on bullet point 4 of the story hasn't been done 
https://docs.google.com/presentation/d/16ybp2FPRZfvZvO4JKMKwmgAQxNfw7NF407RiDjASgPI/edit#slide=id.gb85ebc79ee_0_167

I assume this will need to be done for all 3 same pages (both, vat, duty)

**Comment by dannybassi** [comment]
Seems like bullet 5 has also been missed

https://docs.google.com/presentation/d/1CLkTjo5HU519Lc1bVYUbl1zvjjzDcporNOiGj9RDzn8/edit#slide=id.ge8a7fbf6ac_0_101

**Comment by jacemale-hmrc** [comment]
there are now separate subtasks for the bullets mentioned above, this PR is ready for review again

**Review by dannybassi — APPROVED** [review]

**Comment by dannybassi** [comment]
> Section 2 error messages have been updated on the spreadsheet. Could this also be updated

Completed and approved

**Review by tvaidotas — APPROVED** [review]

**Pull request merged**
